export const FAKE_POPULARS = [
  {
    adult: false,
    backdrop_path: "/jWXrQstj7p3Wl5MfYWY6IHqRpDb.jpg",
    genre_ids: [10763],
    id: 94722,
    origin_country: ["DE"],
    original_language: "de",
    original_name: "Tagesschau",
    overview:
      "German daily news program, the oldest still existing program on German television.",
    popularity: 2775.965,
    poster_path: "/7dFZJ2ZJJdcmkp05B9NWlqTJ5tq.jpg",
    first_air_date: "1952-12-26",
    name: "Tagesschau",
    vote_average: 6.788,
    vote_count: 231,
  },
];
export const FAKE_RECOMMENDATIONS = [
  {
    backdrop_path: "/l7LRGYJY3NzIGBlpvHpMsNXHbm5.jpg",
    id: 218145,
    name: "Mom for rent",
    original_name: "Mama na prenájom",
    overview:
      "Abandoned by his wife, Martin is lying to his daughter not to be upset. But as Hanka grows, these lies become unbearable. Martin meets Nada unexpectedly, asked her to be a rent-a-mother and all lives are completely changed.",
    poster_path: "/fH7PP2Rkdlo414IHvZABBHhtoqd.jpg",
    media_type: "tv",
    adult: false,
    original_language: "sk",
    genre_ids: [10751, 35],
    popularity: 1949.904,
    first_air_date: "2023-01-09",
    vote_average: 5.5,
    vote_count: 32,
    origin_country: ["SK"],
  },
  {
    backdrop_path: "/jVPIY05Fmweb6xjMSQqbjfWg379.jpg",
    id: 46669,
    name: "Skip Beat!",
    original_name: "スキップ・ビート!",
    overview:
      "Kyoko followed her true love and childhood friend Sho to Tokyo so she could help him reach his dream of becoming an idol. She cleans, cooks, works three jobs and does nothing for herself because she loves him so much, but gets nothing in return. Still, she remains by his side. But then one day she goes unannounced to his agency with a delivery, and overhears him talking about her; he reveals to his manager that he only took her with him as a maid, and that he doesn't care for her at all. Upon hearing this, Kyoko doesn't just sit around and cry. She cuts and dyes her hair, changes her clothes and attitude and thus begins her journey to join showbiz and have her revenge against Sho",
    poster_path: "/swcwu5M0xoquONxobt57hWK7U9M.jpg",
    media_type: "tv",
    adult: false,
    original_language: "ja",
    genre_ids: [16, 18, 35],
    popularity: 19.264,
    first_air_date: "2008-10-05",
    vote_average: 7,
    vote_count: 18,
    origin_country: ["JP"],
  },
  {
    backdrop_path: "/kvQE5pvZZWCIQ0uAQvzRmQO3nZM.jpg",
    id: 231344,
    name: "Los 50",
    original_name: "Los 50",
    overview:
      "Fifty TV stars are single handedly picked by a mysterious, masked Lion to participate in a competition like no other. Living together in an exotic country mansion and competing against each other in a relentless and unpredictable game, the stars must face challenges posed by the game master while making alliances and developing strategies to avoid elimination.",
    poster_path: "/5u4lYLk0kDf6XTUIENhXkaUV2jQ.jpg",
    media_type: "tv",
    adult: false,
    original_language: "es",
    genre_ids: [10764],
    popularity: 2392.236,
    first_air_date: "2023-07-18",
    vote_average: 6.893,
    vote_count: 28,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/87aqAZuW3HV7smlQtZA8srcW4aq.jpg",
    id: 237243,
    name: "Big Brother",
    original_name: "Big Brother",
    overview:
      "Britain’s ultimate social experiment. Follow every twist and turn as a group of housemates live under the gaze of 24/7 cameras and try to avoid eviction. Big Brother sees it all...",
    poster_path: "/Tg2g7XvPLWsEbNH0hM1jxMfOmk.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [10764],
    popularity: 136.496,
    first_air_date: "2023-10-08",
    vote_average: 5.8,
    vote_count: 12,
    origin_country: ["GB"],
  },
  {
    backdrop_path: "/hwUQsL1cWt0bmbTxzCompqqvTH9.jpg",
    id: 82250,
    name: "Gran hermano VIP",
    original_name: "Gran hermano VIP",
    overview: "",
    poster_path: "/9269PATr0bmEXKjkpR88mzGmNYI.jpg",
    media_type: "tv",
    adult: false,
    original_language: "es",
    genre_ids: [10764],
    popularity: 34.796,
    first_air_date: "2004-01-22",
    vote_average: 3.9,
    vote_count: 17,
    origin_country: ["ES"],
  },
  {
    backdrop_path: "/eGoX4DFXFtFgvBAdAv3pQSxyHDi.jpg",
    id: 234512,
    name: "Leading Role",
    original_name: "Papel Principal",
    overview:
      "At the center of this story is Aurora Guerra, a popular actress who became a star in the teen series \"The Chosen Ones\" at an early age. Irene and Julio, Aurora's parents, signed her up for a casting several years ago and the matriarch, realizing that the decision was between her and another girl, managed to play the casting director in Aurora's favor. Lúcia has the same dream: to be a successful actress and decides to apply for the casting as well, but she soon realizes Irene's scheme and decides to confront her. After a violent argument between the two, Lúcia ends up having an accident that almost took her life and killed her chance of becoming an actress, due to the physical disabilities she was left with. Twenty years later, Lucia is determined to take revenge. The young woman wants to get back what she believes Aurora has taken from her, far from imagining that she is just a victim of Irene's evil deeds.",
    poster_path: "/t0ZWTCP451IgzMgHSPDBenpLG1W.jpg",
    media_type: "tv",
    adult: false,
    original_language: "pt",
    genre_ids: [18],
    popularity: 52.142,
    first_air_date: "2023-09-25",
    vote_average: 6.3,
    vote_count: 5,
    origin_country: ["PT"],
  },
  {
    backdrop_path: "/aRtLEHMrcbG5InnfL8l3ZdIWS5I.jpg",
    id: 246331,
    name: "Su Ji and U Ri",
    original_name: "수지맞은 우리",
    overview:
      "A healing romance begins between fallen star doctor Jin Su Ji and stubborn newbie doctor Choi U Ri.",
    poster_path: "/bGVdZ8nc99GIwCDxmXpGP0oCSzT.jpg",
    media_type: "tv",
    adult: false,
    original_language: "ko",
    genre_ids: [10751, 18],
    popularity: 129.56,
    first_air_date: "2024-03-25",
    vote_average: 5.8,
    vote_count: 5,
    origin_country: ["KR"],
  },
  {
    backdrop_path: "/mZCq3ldk7hUIyDvfZIOvTrxPWYS.jpg",
    id: 209374,
    name: "Top Chef VIP",
    original_name: "Top Chef VIP",
    overview:
      "Four finalists compete for the grand title of Top Chef VIP and a prize of $200,000.",
    poster_path: "/6Gy1ReRZ9sK9g8TPXZGz7CcQvrV.jpg",
    media_type: "tv",
    adult: false,
    original_language: "es",
    genre_ids: [10764],
    popularity: 43.04,
    first_air_date: "2022-08-09",
    vote_average: 6,
    vote_count: 11,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/vg4QxGpweriMUGkcXNgjbFDqWFK.jpg",
    id: 16395,
    name: "MasterChef Australia",
    original_name: "MasterChef Australia",
    overview:
      "MasterChef Australia is a Logie Award-winning Australian competitive cooking game show based on the original British MasterChef. It is produced by Shine Australia and screens on Network Ten. Restaurateur and chef Gary Mehigan, chef George Calombaris and food critic Matt Preston serve as the show's main judges. Journalist Sarah Wilson hosted the first series, however her role was dropped at the end of the series.",
    poster_path: "/m5akdtbWznF8KpOewKyKw0C36s1.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [10764],
    popularity: 155.042,
    first_air_date: "2009-04-27",
    vote_average: 6.8,
    vote_count: 75,
    origin_country: ["AU"],
  },
  {
    backdrop_path: "/va6iR1UBVvbj9xFKbK1XHvALb98.jpg",
    id: 233952,
    name: "Golden Trio",
    original_name: "老家伙",
    overview:
      "Xiao Chang Qing, Sun Qian Cheng and Chen Xin Cheng worked hard all their lives. After retirement, they finally got together and co-founded a warm retirement community. In the community, they solved problems that elderly people faced, and in the process, they recognized their own problems and reconciled with their family and with themselves",
    poster_path: "/4edgc2TuV3PP7FvFV2zzWDRagNP.jpg",
    media_type: "tv",
    adult: false,
    original_language: "zh",
    genre_ids: [18],
    popularity: 19.125,
    first_air_date: "2024-05-14",
    vote_average: 6.1,
    vote_count: 9,
    origin_country: ["CN"],
  },
];
